FROM apache/spark-py:3.3.1

USER root
# Install pipenv and compilation dependencies
RUN pip3 install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc

WORKDIR /

# Install python dependencies in /.venv
COPY Pipfile .
COPY Pipfile.lock .


RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --dev
ENV PATH="/.venv/bin:$PATH"

RUN useradd --create-home appuser
RUN chmod -R 777 "/.venv/"
WORKDIR /home/appuser
USER appuser

# Install application into container
COPY . .

# Run the executable
ENTRYPOINT ["pipenv", "run", "pytest"]
